### PR TITLE
Add support for sinumerik files (.mpf .spf). Add highlight sync with page scroll

### PR DESCRIPTION
**Pull request by staniska**
I have added support for Sinumerik CNC files. I don't think many people will use this. Highlight sync with page scrolling has also been added (issue https://github.com/bacadra/pulsar-navigation-panel/issues/3 ). I only tested this for Sinumerik files without levels in the list. I'll be glad if this helps you

### CODE REVIEW

**Comment by asiloisad** [comment]
Thank you very much for your contribution. I'm glad to add support for sinumerik grammar, but the #3 is problematic. I have added .visible class for highlighted item, but It's a bit strange now.

**Comment by asiloisad** [comment]
I made some tweaks (like screen position for soft wrapping and folding), range of visible headers (instead of just one), visible header style (colored icon instead of stack-like or current style). I'm quite satisfied now, but I'd be grateful for your opinion. Best Regards, SB.

**Comment by staniska** [comment]
I like changes you made. I think visibility attribute marked by background color is better colored points. Gradient can be used to highlight blocks that are not fully visible.  I'll try to make the visibility highlight more informative in the near future. Can you post some files contained different navigations with levels to test?

**Comment by asiloisad** [comment]
[NP-TEST.md](https://github.com/bacadra/pulsar-navigation-panel/files/12803460/NP-TEST.md)

I have made some lipsum-like markdown file with headers. It will be helpful to test CSS.

**Pull request merged**
